version: '3.8'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - boyfriend-tg-bot:/var/lib/postgresql/data
volumes:
  boyfriend-tg-bot:
    driver: local