bot:
  name: boyfriend_chad_bot
  token: ${BFBOT_TOKEN}
  notifyOnStartup: false
  notifyOnShutdown: false
  defaultLocale: ru

api:
  complimentApiUrl: https://ultragenerator.com/compliment/handler.php
  jokeApiUrl: http://free-generator.ru/generator.php?action=joke
  gameApiUrl: https://games.cdn.famobi.com/html5games/0/3d-free-kick/v080/?fg_domain=play.famobi.com&fg_aid=A1000-100&fg_uid=2ee096ab-4cd7-4f9a-baa9-f58a54413c47&fg_pid=5a106c0b-28b5-48e2-ab01-ce747dda340f&fg_beat=626&original_ref=https%3A%2F%2Fhtml5games.com%2F

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bf_bot
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      # TODO none
      ddl-auto: update
      naming:
        # SnakeCase DB Naming
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    # TODO Work with DB Migration via Liquibase, bot Hibernate
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  codec:
    max-in-memory-size: 10MB
logging:
  level:
    org.rsinitsyn: debug